#!/usr/bin/env python3
"""Assemble the self-contained Kaggle kernel for one Dream-RSI round.

Kaggle runs a single script, but the cube decoder, VOC parser and COCO scorer
must stay identical to the ones the orchestrator uses locally -- a drift
between them would silently invalidate every score in the discovery tree.
So the kernel is generated from the repo modules rather than kept as a copy.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MODULES = ["cube.py", "voc.py", "spectral.py", "augment.py", "coco_eval.py", "submit.py"]   # order matters: voc feeds coco_eval
DROP = re.compile(r"^\s*(from\s+\.|from\s+__future__\s+import)")


def inline(name: str) -> str:
    src = (REPO / "src" / "hod26" / name).read_text().splitlines()
    kept = [ln for ln in src if not DROP.match(ln)]
    return f"# ---- inlined from src/hod26/{name} " + "-" * 30 + "\n" + "\n".join(kept)


def build(round_cfg: dict) -> str:
    driver = (REPO / "kernels" / "hod26_round" / "driver.py").read_text()
    # The driver's own preamble docstring explains the injection; keep it.
    head = (
        '"""Generated by tools/build_kernel.py -- do not edit directly."""\n'
        "from __future__ import annotations\n\n"
        "import json, subprocess, sys\n"
        # Pinned, and checked again in preflight. The adapter, the loss
        # overrides, the classifier remap and the clock guard all reach into
        # ultralytics internals, so an unpinned install lets a release made
        # between building this kernel and running it change behaviour in the
        # middle of an eleven-hour session -- or, worse, not raise at all.
        "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',\n"
        "                'ultralytics==8.4.155', 'pycocotools'], check=False)\n\n"
    )
    # Embed the config as JSON text rather than as a Python literal: json.dumps
    # emits true/false/null, which are not Python names and fail at import.
    blob = json.dumps(round_cfg, indent=2)
    quote = "'" * 3
    if quote in blob:
        raise ValueError("round config would terminate the embedded string literal")
    cfg = f"ROUND_CONFIG = json.loads(r{quote}\n{blob}\n{quote})\n\n"
    return head + "\n\n".join(inline(m) for m in MODULES) + "\n\n" + cfg + driver


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--round-config", required=True, type=Path)
    ap.add_argument("--out-dir", type=Path,
                    default=REPO / "kernels" / "hod26_round" / "build")
    ap.add_argument("--slug", default=None, help="kaggle kernel slug (user/name)")
    ap.add_argument("--kernel-source", action="append", default=[],
                    help="a previous kernel whose output this run continues from; "
                         "its /kaggle/working lands under /kaggle/input/<name>")
    ap.add_argument("--dataset-source", action="append", default=[],
                    help="an extra Kaggle dataset to mount beside the planar "
                         "frames, e.g. a checkpoint another account resumes from")
    args = ap.parse_args()

    cfg = json.loads(args.round_config.read_text())
    args.out_dir.mkdir(parents=True, exist_ok=True)
    script = args.out_dir / "hod26_round.py"
    script.write_text(build(cfg))

    slug = args.slug or "xishengfeng/hod26-round"
    # Kaggle derives the kernel slug from the title and warns when it disagrees
    # with the id, so the title has to spell the same slug or a push can land on
    # a different kernel than intended.
    title = slug.split("/")[-1].replace("-", " ").title()
    (args.out_dir / "kernel-metadata.json").write_text(json.dumps({
        "id": slug,
        "title": title,
        "code_file": "hod26_round.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "competition_sources": [],
        "dataset_sources": ["xishengfeng/hod26-planar", *args.dataset_source],
        "kernel_sources": list(args.kernel_source),
    }, indent=2))
    print(f"wrote {script} ({script.stat().st_size} bytes)")
    print(f"wrote {args.out_dir / 'kernel-metadata.json'}  slug={slug}")


if __name__ == "__main__":
    main()
